default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") {"localhost"} %>
  username: <%= ENV.fetch("RAILS_DB_USER") {""} %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") {""} %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
